Greedy roles
ClemsonCPSC-Discord/ClemBot pull request #295
Opened 2021-03-14 21:40 UTC by zepthro

Simple fix for #155.

I looked into Greedy[str], but you cannot use a Greedy[str] type, so I did the next best thing, I used split(' ').

Here's a few examples of the changes
Old functionality:
![image](https://user-images.githubusercontent.com/49242436/111085088-2900d200-84ec-11eb-9823-9428c284700f.png)
New functionality:
![image](https://user-images.githubusercontent.com/49242436/111085099-38801b00-84ec-11eb-907c-3f6ac7c861e7.png)

2021-03-15 02:10 UTC, Jay-Madden commented on bot/cogs/assignable_roles_cog.py
> +    async def roles(self, ctx, *, input_roles: str = None) -> None:
this needs to be a `greedy[discord.Roles]` converter

2021-03-15 02:11 UTC, Jay-Madden commented on bot/cogs/assignable_roles_cog.py
> +            except BadArgument:  # If RoleConverter failed
we will need to handle this differently for multi roles

2021-03-18 15:04 UTC, Jay-Madden commented on bot/cogs/assignable_roles_cog.py
> +        if input_roles is None or bad_args:
the check for bad args needs to come at the end, you can have a valid role in between invalid ones

2021-03-18 15:08 UTC, Jay-Madden commented on bot/cogs/assignable_roles_cog.py
> +        if input_roles is None or bad_args:
make the default for input_roles an empty list then you can check bad args at the end

2021-03-24 13:56 UTC, Jay-Madden commented
hmm, how does this handle roles with spaces. For example Special Topics

2021-03-28 16:31 UTC, Jay-Madden requested changes
see above question

2021-04-09 14:14 UTC, Jay-Madden commented
Im not convinced of the possibility of this pr in a clean and concise way, what are your thoughts?

2021-04-09 19:17 UTC, zepthro commented
> Im not convinced of the possibility of this pr in a clean and concise way, what are your thoughts?

I agree. I think we should make a comment on #155, but not close the issue. If someone comes along and figures out an elegant solution, then great.
Additionally, we can close this pull. I don't have a solution as of now.

2021-04-09 19:17 UTC, closed without merging